### ISSUE TITLE
Thames-Coromandel District Councils (TCDC), New Zealand

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4045] opened 2018-06-06 14:44 UTC
https://services5.arcgis.com/MYtLmLEStmKgdmln/arcgis/rest/services/Property_Information/FeatureServer/0

**Comment by andrewharvey** [comment] 2018-08-31 04:56
duplicate of #3842

**Closed by andrewharvey** 2018-08-31 04:56 UTC
Labels: MapServer, data-sources
