### ISSUE TITLE
Open-Data Sweden

### ISSUE THREAD

**Issue by bennyjonsson** [openaddresses/openaddresses#2468] opened 2017-01-31 16:02 UTC
Find out if addresses delivered by Swedish kommuns is (or how to make them) Open Data. There is no what so ever information that the data Swedish kommuns is providing this project over services or other media is Open Data and may be used for openaddresses.
BTW According to Malmö kommun they do not have any Open.

Please help use solve this problem, Benny Jonsson Lunds Kommun.

**Comment by boxed** [comment] 2017-08-03 18:52
Lantmäteriets data is now open so should be fine to use.

**Comment by nvkelso** [comment] 2017-08-03 19:42
This looks like a duplicate of https://github.com/openaddresses/openaddresses/issues/2422, closing this one.

**Closed by nvkelso** 2017-08-03 19:42 UTC
