### ISSUE TITLE
Add addresses in Vancouver, WA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1948] opened 2016-09-15 16:25 UTC
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [x] **Review proposed source**
- [x] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment] 2016-09-27 23:33
sent e-mail requesting data (09/27/2016)

**Comment by justinelliotmeyers** [comment] 2016-09-30 15:41
Received e-mail today - data is at cost - will not have open data until 2017.

Your email was forwarded to me to respond.
 
Clark County GIS is the central GIS repository for all of Clark County.
 
Thank you for letting us know about your project.  .   Open Data is important to Clark County GIS and it is something we are planning to address in 2017.   Our first focus will be on publishing our most popular existing datasets on line.  We simply do not have the resources or charter to provide our data to every open data effort.  We are not interested in participating at this time
 
In the meantime, Clark County GIS data is currently available on DVD.  The Situs points can be found on our Dataset 1 DVD.
This DVD is updated monthly and can be purchased for $200.00. 
 
Best,
 
Bob Pool
GIS Manager
Clark County, Washington
1300 Franklin Street
Vancouver, WA 98666
 
360-397-2092 ext. 4654
Bob.Pool@Clark.Wa.Gov

**Comment by nvkelso** [comment] 2016-09-30 17:46
Can you confirm the existing paid data is open licensed? (If we pay for it, can we redistribute it with credit back to them?)

**Comment by justinelliotmeyers** [comment] 2016-09-30 18:29
Just called Mr. Bob Pool (2:29 CST)- Left voicemail.  I also e-mailed him.  So as soon as I hear back I will update everyone.

**Comment by justinelliotmeyers** [comment] 2016-09-30 20:44
Bob E-mailed me this:
We are in the process of updating our licensing.
Clark County does not have any restrictions on use other than those issues covered in the Washington State Public Records Act.
 
We have a pretty simple disclaimer
 
Disclaimer: Clark County does not warrant the accuracy, reliability or timeliness of any information in this system, and shall not be held liable for losses caused by using this information. Portions of this information may not be current or accurate. Any person or entity who relies on any information obtained from this system, does so at their own risk. RCW 42.56.070(9) prohibits releasing and/or using lists of individuals gathered from this site for commercial purposes.
 
Bob

**Comment by nvkelso** [comment] 2016-09-30 22:08
I've emailed Bob asking to purchase the data.

**Comment by nvkelso** [comment] 2016-11-02 04:43
Bob wrote back saying they only take check payment by mail. I'll send him a check.

**Comment by nvkelso** [comment] 2016-11-02 05:08
Before I do that: @iandees can you confirm you did not already send them a check, please?

**Comment by iandees** [comment] 2016-11-02 11:20
@nvkelso I have not sent a check. Go for it!

**Comment by iandees** [comment] 2016-11-02 11:22
...and thanks!

I'm excited: this'll be the first time we buy and release data.

**Comment by nvkelso** [comment] 2016-11-02 21:23
Wosh! Check is in the snail mail. Now the waiting begins.

**Comment by nvkelso** [comment] 2016-11-18 01:44
Still haven't heard back from them.

**Comment by nvkelso** [comment] 2016-11-18 01:45
Statewide data may land in https://github.com/openaddresses/openaddresses/issues/2141.

**Comment by nvkelso** [comment] 2016-11-28 17:47
Heard back from them – they sent the DVD to the wrong street address and it was returned. 

I've clarified my mailing address and they will resend.

**Comment by nvkelso** [comment] 2016-12-01 23:07
Good news! I received the DVD today from Clark County (Vancouver, Washington state).

Now the complication: I actually have no way of reading said DVD. I'll hunt down an old PC or Mac to do that next and upload using the S3 Uploader tool.

**Comment by nvkelso** [comment] 2016-12-05 22:15
@migurski says he has a DVD reader at home, and has the disk now.

**Comment by migurski** [comment] 2016-12-07 06:00
I have unearthed one of our old laptops, transferred the DVD contents to a thumb drive, and will bring it in for you tomorrow.

**Comment by nvkelso** [comment] 2016-12-07 06:09
And an office DVD reader should arrive Friday :)

**Comment by migurski** [comment] 2016-12-07 06:21
💿

**Comment by migurski** [comment] 2016-12-07 06:23
http://www.newegg.com/Product/Product.aspx?Item=9SIA8R64671887&cm_re=floppy_usb-_-0N6-004E-000H3-_-Product

**Comment by nvkelso** [comment] 2016-12-07 06:30
💾

**Comment by nvkelso** [comment] 2016-12-08 23:11
Data is uploaded to S3 here:

- https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/2806bc/clark_county_vancouver_wa_tax_parcels.zip

Usual caveat about using SITUS address instead of mailing address, and don't export the owner names.

<img width="600" alt="screen shot 2016-12-08 at 15 09 19" src="https://cloud.githubusercontent.com/assets/853051/21031484/9a3c0030-bd58-11e6-8404-6428f67fb010.png">

![screen shot 2016-12-08 at 15 09 06](https://cloud.githubusercontent.com/assets/853051/21031485/9a52c27a-bd58-11e6-902f-4b8895c01740.png)

**Closed** 2016-12-09 00:45 UTC
Labels: data-priority-1, Paid Source, ready for PR
