### ISSUE TITLE
Update Brazilian addresses to use census 2022

### ISSUE THREAD

**Issue by plentz** [openaddresses/openaddresses#7251] opened 2024-05-28 17:13 UTC
Right now, openaddresses use 2010's data. We [can update it to 2022](https://www.ibge.gov.br/estatisticas/sociais/populacao/38734-cadastro-nacional-de-enderecos-para-fins-estatisticos.html?=&t=downloads). cc @astoff @vgeorge

Related:
- https://github.com/openaddresses/openaddresses/issues/2996
- https://github.com/openaddresses/openaddresses/issues/5775
- https://github.com/openaddresses/openaddresses/issues/6038
- https://github.com/openaddresses/openaddresses/pull/5482
- https://github.com/openaddresses/openaddresses/issues/2303

**Comment by ThierryAJean** [comment] 2024-05-31 15:34
Hi @plentz It is a good idea to integrate this data which was published last week by the IBGE. At the [AddressForAll](https://addressforall.org/) Institute, we are planning to improve it and to publish it too in Openaddresses.io. This is particularly relevant as Overture Maps foundation is starting to recompile this data from Openaddresses.io and plans to publish it too, checking with more attention the license.
Considering the flood in Rio Grande do Sul state, we are in the process of doing a POC filtering the data of Porto Alegre, in order to see the result. If ok, we'll do it for the whole country. What do you think? Feel free to contact me +55 11 996071319 (WhatsApp).

**Comment by justinelliotmeyers** [comment] 2024-06-03 12:26
@plentz I looked at this data several weeks ago, and the geometry of the data looked great! I didn't see any attributes for the addresses however. I will have to dedicate more time to look into it, but there are attributes for the actual addresses, right?

thanks for filing the issue to update!!

**Comment by plentz** [comment] 2024-06-03 13:28
@ThierryAJean that's great! Will add you on whatsapp later today

@justinelliotmeyers they do! Bellow I show the files we want (on per state - there's also a version per city, but not worth using them since they have the same data, just more separated)

<img width="675" alt="Screenshot 2024-06-03 at 9 19 45 AM" src="https://github.com/openaddresses/openaddresses/assets/4867/67cd78c2-e59d-4876-9aac-2022bca0302d">

This file `Dicionario_CNEFE_Censo_2022.xls` contains the description of the headers of those files, in portuguese. I can help translate this file if needed.

**Comment by justinelliotmeyers** [comment] 2024-06-03 13:47
@plentz thank you!!!

**Comment by astoff** [comment] 2024-06-04 14:24
Just for the record, I'm interested in this and I can prepare the data for OpenAddresses, but in this case it would have to wait a couple of months.

**Comment by camcima** [comment] 2024-10-04 20:49
I've already created the files for each state based on the 2022 version of CNEFE, derived from Census 2022. The original files from IBGE won`t work because they do not contain city or state names, only codes. I've tried to keep the file format as close as possible to the 2010 version. For now, I've put the files in my [Google Drive](https://drive.google.com/drive/folders/1kBCKhsG6-5fuSBLoRBBW8lLbdk6r8dIv?usp=sharing), but we would need to upload the files to the `data.openaddresses.io` server. Can anyone help me with that? @astoff

**Comment by iandees** [comment] 2024-10-06 21:18
You can use the following URLs:

* https://data.openaddresses.io/cache/uploads/iandees/49a59b/11_RO.zip
* https://data.openaddresses.io/cache/uploads/iandees/a434e4/12_AC.zip
* https://data.openaddresses.io/cache/uploads/iandees/9eb872/13_AM.zip
* https://data.openaddresses.io/cache/uploads/iandees/91af9f/14_RR.zip
* https://data.openaddresses.io/cache/uploads/iandees/5af831/15_PA.zip
* https://data.openaddresses.io/cache/uploads/iandees/3ae378/16_AP.zip
* https://data.openaddresses.io/cache/uploads/iandees/6057f9/17_TO.zip
* https://data.openaddresses.io/cache/uploads/iandees/c0205f/21_MA.zip
* https://data.openaddresses.io/cache/uploads/iandees/1eed61/22_PI.zip
* https://data.openaddresses.io/cache/uploads/iandees/4448c9/23_CE.zip
* https://data.openaddresses.io/cache/uploads/iandees/c38c9e/24_RN.zip
* https://data.openaddresses.io/cache/uploads/iandees/b61e03/25_PB.zip
* https://data.openaddresses.io/cache/uploads/iandees/fa9486/27_AL.zip
* https://data.openaddresses.io/cache/uploads/iandees/ffdeec/28_SE.zip
* https://data.openaddresses.io/cache/uploads/iandees/0c05c6/32_ES.zip
* https://data.openaddresses.io/cache/uploads/iandees/9b2494/35_SP.zip
* https://data.openaddresses.io/cache/uploads/iandees/1e0b2f/42_SC.zip
* https://data.openaddresses.io/cache/uploads/iandees/dc15a3/43_RS.zip
* https://data.openaddresses.io/cache/uploads/iandees/c5e3c6/50_MS.zip
* https://data.openaddresses.io/cache/uploads/iandees/4612f1/51_MT.zip
* https://data.openaddresses.io/cache/uploads/iandees/8de3a0/52_GO.zip
* https://data.openaddresses.io/cache/uploads/iandees/3a0edc/53_DF.zip

**Comment by camcima** [comment] 2024-10-06 23:40
Thanks! I'll work on the PR then.

**Comment by camcima** [comment] 2024-10-07 00:58
Hi @iandees, I've just noticed you missed a few files:
- .../26-PE.zip
- .../29-BA.zip
- .../31-MG.zip
- .../33-RJ.zip
- .../41-PR.zip

**Comment by iandees** [comment] 2024-10-07 01:20
Ok, updated the list with the missing files.

**Comment by astoff** [comment] 2024-10-07 06:46
@camcima 

I noticed that the unique ID column in your CSVs got converted to a float, with loss of precision.

Also, out of curiosity, how did you merge the address and the coordinates files (which is missing a unique ID column)? I supposed it was Just by lining up the rows, which makes sense, but might require some manual checking — did you do a sanity check?

> I've tried to keep the file format as close as possible to the 2010 version.

I had to invent those header names, but now the CSV files come with reasonable header names, so it might make sense to keep those.

**Comment by astoff** [comment] 2024-10-07 06:49
By the way, I noticed that the address data is also available in GeoJSON format from the official source, which could be used directly without any conversions. Maybe we should consider using that instead.

Here's how one entry looks like:

![Screenshot from 2024-10-07 08-41-29](https://github.com/user-attachments/assets/db78c032-45b3-4c83-abd4-cb1f3ce3ec5e)

Apart from having to split the `LOGRAD_NUM` field as `{street name}, {number}` and requiring an ID lookup for state and municipality (only IDs are listed) it looks pretty usable.

**Comment by camcima** [comment] 2024-10-07 11:43
Hi @astoff, 

Let me break it down by topics:

**Unique ID**: The unique ID I used is the `COD_UNICO_ENDERECO` column in the original data source. I'm going to investigate why this is happening. Do you have an example?

**Merge Address and Coordinates**: The original CSV file already comes with both in each row. Different from the Census 2010, the coordinate is specific for each address, and not to the face of the block, so no merging is needed.

**Header Names**: I'll revert back to the original names then. I thought it would be better in English so more people would understand but it makes sense to keep them original.

**GeoJSON**: The GeoJSON file is much simpler than the CSV file, with way less fields. If you prefer the GeoJSON format, I would generate it from the CSV, as I have all the fields already separated and it would be better to join them, then to try to split them. Also, the order in which the fields were joined in the GeoJSON is not right in my opinion. For instance, when we have the `address modifier` (`DSC_MODIFICADOR`) KM, in the GeoJSON it appears after the number, which in portuguese doesn't make a lot of sense. We don't say "RODOVIA BR-116, 24 KM", we say "RODOVIA BR-116, KM 24".

I'll change the header columns and use the GeoJSON format and make it available on my Google Drive, so @iandees can update the cache.

**Comment by astoff** [comment] 2024-10-07 11:53
Ah, sorry, I missed that the original CSV already includes the coordinates!  This is great, actually. It means there's no need to upload a cleaned version of the data to an intermediate place. We can make the OA machine get the data straight from the original source at https://ftp.ibge.gov.br/Cadastro_Nacional_de_Enderecos_para_Fins_Estatisticos/Censo_Demografico_2022/Arquivos_CNEFE/CSV/UF/

**Comment by camcima** [comment] 2024-10-07 13:44
The problem is that the original file does not include city and state, only codes.

**Comment by camcima** [comment] 2024-10-07 14:49
I've already generated the new files, aiming to keep the original headers as much as possible, resolving municipality, district and subdistrict codes, and outputting it in a csv format. This is sample of the final result:

```csv
COD_UNICO_ENDERECO,UF,DISTRITO,SUBDISTRITO,MUNICIPIO,COD_SETOR,NUM_QUADRA,NUM_FACE,CEP,DSC_LOCALIDADE,LOGRADOURO,NUM_ENDERECO,COMPLEMENTO,LATITUDE,LONGITUDE,NV_GEO_CO
ORD,COD_TIPO_ESPECI,DSC_ESTABELECIMENTO,COD_ESPECIE
208432758,SP,Terra Preta,,Mairiporã,352850215000063P,5,6,07661410,CENTRO,RUA JOSE RIBEIRO BEZERRA,64,SOBRADO 64,-23.268618,-46.586949,1,,,7
208432760,SP,Terra Preta,,Mairiporã,352850215000063P,5,6,07661410,CENTRO,RUA JOSE RIBEIRO BEZERRA,92,CASA 92,-23.268527,-46.587026,1,101,,1
208432763,SP,Terra Preta,,Mairiporã,352850215000063P,5,6,07661410,CENTRO,RUA JOSE RIBEIRO BEZERRA,185,CASA 185 FUDOS,-23.267537,-46.586968,1,101,,1
93601316,SP,Lorena,,Lorena,352720705000248P,7,13,12602810,CAMPINHO,RUA A,115,CHACARA VITORIA DA,-22.690205,-45.105361,1,101,,1
54157513,SP,Osasco,,Osasco,353440105001600P,2,4,06140030,CONCEICAO,RUA PAULISTA,329,CASA 2,-23.575329,-46.801904,1,101,,1
```

The updated zipped files are already in my Google Drive and I would need to update the files in the `data.openaddresses.io` server in order to change my PR. @iandees, can you please help me with that?

**Comment by iandees** [comment] 2024-10-09 14:37
New URLs:

* https://data.openaddresses.io/cache/uploads/iandees/94a5d3/11_RO.zip
* https://data.openaddresses.io/cache/uploads/iandees/251f65/12_AC.zip
* https://data.openaddresses.io/cache/uploads/iandees/b40ad6/13_AM.zip
* https://data.openaddresses.io/cache/uploads/iandees/a27de2/14_RR.zip
* https://data.openaddresses.io/cache/uploads/iandees/0fd80b/15_PA.zip
* https://data.openaddresses.io/cache/uploads/iandees/a8b836/16_AP.zip
* https://data.openaddresses.io/cache/uploads/iandees/266670/17_TO.zip
* https://data.openaddresses.io/cache/uploads/iandees/fc378a/21_MA.zip
* https://data.openaddresses.io/cache/uploads/iandees/065520/22_PI.zip
* https://data.openaddresses.io/cache/uploads/iandees/7104b3/23_CE.zip
* https://data.openaddresses.io/cache/uploads/iandees/9f2269/24_RN.zip
* https://data.openaddresses.io/cache/uploads/iandees/9004be/25_PB.zip
* https://data.openaddresses.io/cache/uploads/iandees/21454e/26_PE.zip
* https://data.openaddresses.io/cache/uploads/iandees/0ca4a4/27_AL.zip
* https://data.openaddresses.io/cache/uploads/iandees/52c9ab/28_SE.zip
* https://data.openaddresses.io/cache/uploads/iandees/29564c/29_BA.zip
* https://data.openaddresses.io/cache/uploads/iandees/f7c31a/31_MG.zip
* https://data.openaddresses.io/cache/uploads/iandees/fbcad4/32_ES.zip
* https://data.openaddresses.io/cache/uploads/iandees/36c698/33_RJ.zip
* https://data.openaddresses.io/cache/uploads/iandees/b258c8/35_SP.zip
* https://data.openaddresses.io/cache/uploads/iandees/7b86c8/41_PR.zip
* https://data.openaddresses.io/cache/uploads/iandees/30f904/42_SC.zip
* https://data.openaddresses.io/cache/uploads/iandees/17adfe/43_RS.zip
* https://data.openaddresses.io/cache/uploads/iandees/dde36e/50_MS.zip
* https://data.openaddresses.io/cache/uploads/iandees/fd6c2a/51_MT.zip
* https://data.openaddresses.io/cache/uploads/iandees/6afa85/52_GO.zip
* https://data.openaddresses.io/cache/uploads/iandees/38d487/53_DF.zip

**Comment by camcima** [comment] 2024-10-10 00:39
The PR #7455 was already updated.

**Comment by camcima** [comment] 2024-10-10 14:18
The PR has been merged and tis issue can be closed. Thanks a lot @iandees, @astoff and @ThierryAJean for your help and support!

**Closed** 2024-10-10 14:21 UTC

**Comment by justinelliotmeyers** [comment] 2024-10-21 13:22
@camcima @ThierryAJean can you assist me with two other datasets I am looking for in Brazil? Building footprints and cadastral parcels? 

Thank you!

**Comment by ThierryAJean** [comment] 2024-10-21 14:34
@justinelliotmeyers, the best Building footprints you will get are available on Overture which gathers building footprints from MS, TomTom, Google and OSM. For cadastral parcels, I don't think there is a national DB in Brazil, yet. It may become available with the SINTER project from Receita Federal Brasileira in the future.

**Comment by ThierryAJean** [comment] 2025-08-27 23:27
@iandees We (AddressForAll Institute) have a national database for the whole of Brazil. We have taken the CNFE / IBGE data, and we have eliminated duplicates, reducing the number of addresses to 95 millions+-. This database contains the Neighborhhods. The link for download is here: https://www.dropbox.com/scl/fi/gbfkot4dtx5u3cl2nktjg/CNEFE_With_Neighbourhood_20250820.csv?rlkey=7pmirxpl5rwji1kbuodd7yfly&st=b329i8vc&dl=0 
The license clarification document is here.  https://addressforall-my.sharepoint.com/:b:/g/personal/thierry_addressforall_org/EeOB2M_fyKpKu-X4hg7cQVwBqilUGPyBIJcWpcRyYOSLSQ?e=IlV6Tv 
@jeffdefacto Check what is best to do for Overture too.

**Comment by iandees** [comment] 2025-11-08 14:37
@ThierryAJean sorry for the late reply. I just noticed this post on an old issue. If there's new content to add, can you please create a new issue or make a change with a pull request? Thanks!
