### ISSUE TITLE
Plumas County, California

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2145] opened 2016-11-20 01:24 UTC
![plumas_county](https://cloud.githubusercontent.com/assets/5324316/20459606/e23fb9ac-ae95-11e6-87d7-fe36f15ddbb2.png)

Anyone want to convert the kml for address points to a csv/ json?

http://www.countyofplumas.com/index.aspx?NID=2192

terms here:
Liability Disclaimer and Use Restrictions: 

The data accessed through this website provides a visual display of geographical information as a public resource of general information for use "AS IS,” "AS AVAILABLE" and "WITH ALL FAULTS" basis. The data presented are aggregated from a wide variety of sources. We have attempted to integrate these various data sources as well as possible. Each agency providing data may have their own internal standards for accuracy and timeliness, thus the GIS division cannot guarantee the degree to which the various data sources agree with each other. While every reasonable effort has been made to ensure the content, sequence, accuracy, timeliness or completeness of materials presented within this data, Plumas County GIS shall assume no liability for: 1. Any errors, omissions, or inaccuracies in the information provided, regardless of how caused; or 2. Any decision made or action taken or not taken by user in reliance upon any information or data furnished hereunder. 

In any situation where the official printed publications of Plumas County differ from the text or graphical representations contained in this system, the official printed documents take precedence. If misleading, inaccurate or otherwise inappropriate information is brought to the County’s attention, a reasonable effort will be made to fix or remove it. 

By using the Plumas County GIS Online web page and Interactive GIS Web Map, you assume all risks associated with the use of this site including any risk to your computer, software or data being damaged by any virus, software, or any other file, which might be transmitted or activated via Plumas County page or your access to it. Therefore, by using this website for any purpose, users agree to indemnify, defend, and hold Plumas County harmless for any and all liability of any nature arising out of or resulting from the lack of accuracy or correctness of the data, or the use of the data presented on the website. 

Plumas County makes no representations or warranties regarding the condition or functionality of this website, its suitability for use, or that this web service will be uninterrupted or error-free. 

Use Restrictions:

Plumas County KML/KMZ data: Plumas County GIS is only providing the data to be used in the Google Earth application on the user's computer. We are not responsible for installing or maintaining this software product.
All GIS data have inherent spatial inaccuracies, including aerial imagery. Sometimes, the aerial data (which is based on latitude and longitude coordinates acquired before the flight) will not match correctly with parcel or road data and may have varying degrees of accuracy. Aerial images may have feature displacement and scale variation caused by differences in elevation, lens distortion, and camera tilt. Parcel boundary lines should be considered a graphical representation and not in any way a legal survey or engineering document.
The Google Earth imagery dates provided do not necessarily represent the date the image was captured but show the date the imagery was processed and deployed.
This data is for visual representation only and may not contain all data that is available by contacting Plumas County Planning Services or GIS directly.
The Plumas County GIS data is for informational purposes only and should not be used to determine precise boundaries, parcel boundaries, appraisal, engineering, nor legal descriptions. The Plumas County GIS data shall not be construed to be an official survey. Site specific evaluation should be verified by field inspection. In addition, land information is constantly changing and the most current or accurate data might not be represented herein.
Primary sources from which this data was compiled must be consulted for verification of information contained in this data. Contact the appropriate County Department to obtain original source documents or for official determinations. You may also contact the Plumas County Planning Services at (530) 283-7011 for more information.
External links: This website contains links to other websites on the Internet; they are provided as a convenience to you. The inclusion of links on this website, however, should not be construed as an endorsement by Plumas County of those links and their contents. Please be aware that we do not control or guarantee the accuracy, relevance, timeliness, or completeness of this outside information.

Read the liability disclaimer and use restrictions carefully.  By clicking the "I ACCEPT" button, you agree that you have read and understand the preceding information and you will be able to enter the online mapping and data download page.  By clicking the "REJECT" button, you DO NOT agree to the preceding information and will be returned to Plumas County's GIS Home Page.

**Comment by davidchiles** [comment] 2016-11-29 02:03
Made a quick script to convert the Plumas County kmz to csv. https://github.com/davidchiles/plumas-address

Where do you want to put the csv for hosting?

**Comment by nvkelso** [comment] 2016-11-29 04:45
@davidchiles Are you able to use https://results.openaddresses.io/upload-cache?

@migurski I get the same error as Justin after authenticating and falsely see:

`Error logging in: you need to be a member of the OpenAddresses Github organization.`.

**Comment by migurski** [comment] 2016-11-29 06:32
Grar, I'm going to need to figure out how to debug this. It seems to hinge on whether you are a public or private member of the group.

**Comment by nvkelso** [comment] 2016-11-29 07:44
Confirmed: I made my membership public (didn't realize it was default private) and now I can login.

**Comment by nvkelso** [comment] 2016-11-29 07:47
@davidchiles Looks like your lat & lon fields are reversed. Current setup plots them south of Antarctica!

**Comment by nvkelso** [comment] 2016-11-29 07:49
I've fixed locally and uploaded to:

- https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/e8ef1c/plumas_california_usa_kmz_csv_results.csv

**Comment by davidchiles** [comment] 2016-11-29 08:02
@nvkelso Thanks! Fixed in the script now.

**Comment by justinelliotmeyers** [comment] 2016-11-29 11:15
thanks @davidchiles for converting the kml!!

**Closed** 2016-11-29 18:58 UTC
Labels: data-priority-2, data-sources, ready for PR

**Comment by migurski** [comment] 2016-11-30 01:14
Thanks @nvkelso! Sorry about the public/private issue, I will attempt a fix.
