### ISSUE TITLE
rogue source

### ISSUE THREAD

**Issue by missinglink** [openaddresses/openaddresses#6000] opened 2022-02-03 09:32 UTC
I've seen this in the API responses too, seems out of place?

<img width="1051" alt="Screenshot 2022-02-03 at 10 31 31" src="https://user-images.githubusercontent.com/738069/152316412-970c6dfd-e811-4e92-b81e-ff34ef576791.png">

**Comment by ingalls** [comment] 2022-02-03 16:38
@missinglink Yeah I noticed that yesterday but not sure how it snuck through. Starting digging last night - I'll update here what I find. 

Once I find root cause I don't currently have any way of actually removing these - so will have to build out a light API to hide these.

**Comment by missinglink** [comment] 2022-04-21 16:19
Spotted again today:

<img width="1040" alt="Screenshot 2022-04-21 at 18 17 05" src="https://user-images.githubusercontent.com/738069/164505615-ee883e09-54e4-4a44-8c05-e23f38d35c82.png">

**Comment by ingalls** [comment] 2022-05-04 18:51
```
https://raw.githubusercontent.com/openaddresses/openaddresses/f2b17bfead53aeb57c4f85af8457448f317199b7/sources/us/wy/laramie.json
```

vs

```
https://github.com/openaddresses/openaddresses/raw/77935669fa7290ffc9f3cd4696fd22b58b5f5a2a/sources%2Fus%2Fco%2Fsummit.json
```

Github appears to have changed the format that URLs are passed in their webhooks. File paths are now URL encoded :/

**Comment by ingalls** [comment] 2022-05-04 23:56
This is now fixed on the processing end. I've got to add a UI/API option to allow manual removal of a source from the `/data` endpoint.

**Closed** 2022-05-07 18:47 UTC
